# Generated by Django 4.2.13 on 2024-06-22 04:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=255, unique=True),
        ),
    ]
