# Generated by Django 4.2.13 on 2024-06-22 05:04

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='code',
            field=models.CharField(default=chat.models.generate_unique_key, editable=False, max_length=6, unique=True),
        ),
    ]
