# Generated by Django 4.2.13 on 2024-06-22 05:05

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=255),
        ),
    ]
