# Generated by Django 4.2.13 on 2024-06-26 16:20

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='code',
            field=models.CharField(default=chat.models.generate_unique_key, editable=False, max_length=6),
        ),
    ]
