# Generated by Django 4.2.13 on 2024-07-14 14:21

import chat.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatroom_code_alter_chatroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='code',
            field=models.CharField(default=chat.models.generate_unique_key, editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=255),
        ),
    ]
