# Generated by Django 4.2.13 on 2024-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatroom_code_alter_chatroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='code',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
